export PATH="/raid3/projects/CARDIPS/software/bedtools2-2.23.0/bin:$PATH"
export PATH="/raid3/projects/CARDIPS/software/R-3.1.1/bin:$PATH"
export LDFLAGS="-Wl,-rpath,/raid3/projects/CARDIPS/software/R-3.1.1/lib64/R/lib"
export LD_LIBRARY_PATH="/raid3/projects/CARDIPS/software/R-3.1.1/lib64/R/lib:$LD_LIBRARY_PATH"
export PATH="/raid3/projects/CARDIPS/software/homer/bin:$PATH"
export PATH="/raid3/projects/CARDIPS/software/samtools-bcftools-htslib-1.0_x64-linux/bin:$PATH"
export PATH="/raid3/projects/CARDIPS/software/weblogo:$PATH"
export PATH="/raid3/projects/CARDIPS/software/:$PATH"
